apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: "/mnt/my-persistent-storage"
          name: my-storage
      volumes:
      - name: my-storage
        nfs:
          server: nfs-server.default.svc.cluster.local
          path: /
